### ISSUE TITLE
Problems in graphics bei coxph with one covariate 

### ISSUE THREAD

**Issue by helmutkuechenhoff** [wolfganglederer/simex#7]

**Comment by helmutkuechenhoff** [comment]
When using the Simex with one Covariate, then the graphics does not work. Maybe because there is no intercept for cox, see my testing code. 
[simexcox1.zip](https://github.com/wolfganglederer/simex/files/3441230/simexcox1.zip)

**Comment by wolfganglederer** [comment]
Fixed by 941f4aae18f6bc23a7ca5145889171ad1d21c42f
